# Generated by Django 2.2 on 2022-10-19 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='day_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='day_to_be_completed',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='task',
            name='is_task_completed',
            field=models.BooleanField(default=False),
        ),
    ]
